// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": import.meta.env.VITE_AWS_REGION || "us-east-1",
    "aws_cognito_identity_pool_id": import.meta.env.VITE_AWS_IDENTITY_POOL_ID || "",
    "aws_cognito_region": import.meta.env.VITE_AWS_REGION || "us-east-1",
    "aws_user_pools_id": import.meta.env.VITE_AWS_USER_POOL_ID || "",
    "aws_user_pools_web_client_id": import.meta.env.VITE_AWS_USER_POOL_WEB_CLIENT_ID || "",
    "aws_appsync_graphqlEndpoint": import.meta.env.VITE_API_URL || "https://main.dcxnozgl43fjs.amplifyapp.com/",
    "aws_appsync_region": import.meta.env.VITE_AWS_REGION || "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": import.meta.env.VITE_TON_API_KEY || ""
};


export default awsmobile;
