/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c9d23d7c-961a-4f50-8260-94a52207890f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_I7xWOpRDb",
    "aws_user_pools_web_client_id": "7a0msvlm15qhoau4hh5qlje8l",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-lisaairdropgame-main-ea6e2-deployment",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
